[build]
  publish = "public"
  command = "npm run build:netlify"
[context.production]
  environment ={  KONTENT_PROJECT_ID = "56252ba5-6f31-02e9-1095-40b19af050ee", KONTENT_LANGUAGE_CODENAMES = "en-US, cs-CZ" }
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
